Fix clippy warnings related to uninlined format! args
Which output the following error message:

```
error: variables can be used directly in the `format!` string
```

The fix was to simply add the variable names inside the template string
instead of giving them as separate arguments.