Fix failing Linux builds with aarch64 and armv7 targets
The cross compilation failed due to cargo calling the host linker, which
produced errors such as:

```
error: linking with `cc` failed: exit status: 1
```

```
/usr/bin/ld: /home/runner/work/basalt/basalt/target/armv7-unknown-linux-gnueabihf/release/deps/basalt-68cb636f749dc709.basalt.1a71d1a4a2ff0e84-cgu.00.rcgu.o: relocations in generic ELF (EM: 40)
```

```
/usr/bin/ld: /home/runner/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-musl/lib/self-contained/crt1.o: Relocations in generic ELF (EM: 183)
```

These issues were fixed by providing correct linker to each affected
target in `.cargo/config.toml` file.